name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build library
        run: cargo build --release

      - name: Run tests
        run: cargo test --release

      - name: Upload dynamic libraries
        uses: actions/upload-artifact@v4
        with:
          name: shared-libs-${{ matrix.os }}
          path: |
            target/release/*.dll
            target/release/*.so
            target/release/*.dylib
          if-no-files-found: ignore